### ISSUE TITLE
Possibility to install as PIP module

### ISSUE THREAD

**Issue by noway421** [piqueserver/piqueserver#1]
Not sure whether this is in the road map, but it'd be nice to make it a pypi package and be able to install it using pip.

Here's the very basic support for that, but it's not even possible to run the server this way IIRC https://github.com/NateShoffner/PySnip/pull/16

**Comment by noway421** [comment]
Last time I checked it involved a lot of problems with directory structure and paths. It is an issue which would involve going through the whole codebase and fixing the path construction/handling everywhere to get it working. 

Even then there might be some architectural issues.

Not sure whether if it's possible to do that for `0.1`. Unfortunately I'm not able to provide commitment to work on that issue. It'd be definitely rad if someone would take on that venture.

**Comment by feikname** [comment]
I didn't look at the codebase yet, but it's probably true, so I am changing the milestone to "Someday"

**Comment by swalladge** [comment]
This is also resolved with the new pypi package working! :)
