### ISSUE TITLE
Turn `pyspades/server.py loader_recieved` into a dictionary instead of `if-elif` spam

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#103]
Turn `pyspades/server.py loader_recieved` into a dictionary instead of `if-elif` spam

Very simple but tedious to do. Should speed things up as well as making everything a lot more sane.

**Comment by feikname** [comment]
@notafile I believe you made a typo.

**Comment by NotAFile** [comment]
@feikname what where?
