### ISSUE TITLE
Get rid of `pyspades/types.py`

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#105]
This file consists almost exclusively of types that are completely pointless.

One example is this gem:
```python
class AttributeSet(set):
    """
    set with attribute access, i.e.

        foo = AttributeSet()
        foo.bar = True
        foo.bar == 'bar' in foo == True
        foo.bar = False
        foo.bar == 'bar' in foo == False

    This works as a quick shorthand for membership testing.
    """

    def __getattr__(self, name):
        return name in self

    def __setattr__(self, name, value):
        if value:
            self.add(name)
        else:
            self.discard(name)
```

**Comment by NotAFile** [comment]
The worst offender here is `MultiKeyDict`, which essentially turns the nice probable O(1) of a dictionary into an O(n) search every time you want to get a player by name or ID. The authors rationale was aparently not needing two dicts, but it's fair to say that this is not a good design decision.

**Comment by swalladge** [comment]
All useless types removed. :)
