### ISSUE TITLE
Allow using custom team names in commands.

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#111]
currently, this is the way commands deal with teams:

```
    def get_team(connection, value):
        value = value.lower()
        if value == 'blue':
            return connection.protocol.blue_team
        elif value == 'green':
            return connection.protocol.green_team
        elif value == 'spectator':
            return connection.protocol.spectator_team
        raise CommandError("Invalid Team")
```

This means that these command are hard to use with custom team colors or names

**Comment by xtreme8000** [comment]
Maybe internals should be renamed aswell, like from `blue_team` to `team_1`

**Comment by feikname** [comment]
I agree with @xtreme8000, but we by deprecating them instead of removing.

**Comment by kmsiapps** [comment]
Can we use `config.get("team1").get("name")` there?

**Comment by NotAFile** [comment]
It's much simpler. You can just do `server.team_blue.name` or vice versa for team green. I agree the names suck though and should be deprecated/aliased to team_1 and team_2, or a better system that allows for more or less teams.
