### ISSUE TITLE
Merge `goto` and `move` commands

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#112]
These commands currently do pretty much exactly the same thing

**Comment by feikname** [comment]
Proposed change: 
```text
/goto <sector> [player]
/goto <x> <y> <z> [player]
```

`/move` gets completely removed in my proposal to reduce number of duplicated commands, but it might be nicer to alias it.

**Comment by NotAFile** [comment]
I think in my head calling it "move" makes more sense
