### ISSUE TITLE
Admin commands output

### ISSUE THREAD

**Issue by dgadelha** [piqueserver/piqueserver#122]
One of the things I asked myself when using PySnip was if there was really a need of showing to everyone what an admin is doing (commands).

For some commands, like togglebuild, toggleteamkill, there is really a need of noticing players. But using goto, tp, god (even though there's a silent for these), kill, heal, it would be okay to show only to the other admins, but showing to everyone is a bit unneeded.

**Comment by dgadelha** [comment]
Also, something I'd like to report. When a player join the server the ping goes high for everyone who's already connected. Like, normally the ping is ~150 ms. When someone is connecting, ping goes to ~ 900 ms. Had to go back to PySnip due to that.

**Comment by dgadelha** [comment]
And I found many issues with scripts like medkit (crash), airstrike (unknown command), nointelonwalls (couldn't get the intel), nospadingwalls (crash), and some others that I don't remember now.

**Comment by NotAFile** [comment]
Yes, many scripts are currently untested, unfortunately.

I wonder what's causing the high ping. It seems to be working just fine for our test server, with little complaints.

Could you open these as separate issues?

**Comment by NotAFile** [comment]
The actual admin notification part is a hard thing.

Showing messages prevents admin abuse and for most commands, there is just no reason to run them silently if not cheating, e.g. /heal. What commands would you like to do silently?

If we added some kind of "silence" prefix, this complicates things as well. Scripts may do pretty much anything in commands and this means it might suppress potentially crucial output.

**Comment by dgadelha** [comment]
Alright, created #124 and #125.

About the admin commands, well, I wish that the admin could just manage the server without letting everyone know what they're doing. I know that this could lead into cheating, but well, I wouldn't make someone who's a bad admin, an admin.

There could be at least an option for that.
