### ISSUE TITLE
Many scripts are broken

### ISSUE THREAD

**Issue by dgadelha** [piqueserver/piqueserver#124]
I have decided to replace this issue with our checklist so it shows up nicely -nota

Script testing checklist:
Note: Please report the Traceback in chat when you mark a script as broken -godwhoa

Gamemodes: 100% 🎉 
- [x] arena.py
- [x] babel_script.py
- [x] babel.py
- [x] push.py
- [x] tdm.py
- [x] freeforall.py
- [x] onectf.py
- [x] tow.py
- [x] infiltration.py (from memory, this was broken on pyspades even. Game refused to start)

General purpose: 100% 🎉 
- [x] afk.py
- [x] autohelp.py
- [x] daycycle.py
- [x] disco.py
- [x] geoip.py
- [x] map_extensions.py
- [x] medkit.py
- [x] memcheck.py
- [x] paint.py
- [x] protect.py
- [x] ratio.py
- [x] spawn_protect.py
- [x] timedmute.py
- [x] welcome.py
- [x] airstrike2.py
- [x] grownade.py
- [x] runningman.py
- [x] demolitionman.py
- [x] dirtnade.py
- [x] antijerk.py
- [x] rollback.py
- [x] flagreturn.py
- [x] squad.py
- [x] votekick.py
- [x] trusted.py
- [x] match.py
- [x] zoc.py
- [x] blockinfo.py
- [x] passreload.py
- [x] markers.py ❌color not working, but good enough
- [x] rampage.py 
- [x] rapid.py
- [x] votemap.py
- [x] rangedamage.py
- [x] strongblock.py
- [x] minefield.py (works, but collides with smartnade)
- [x] smartnade.py
- [x] spectatorcontrol.py
- [x] savemap.py
- [x] mapmakingtools.py
- [x] badmin.py

Patches: 3/5
- [x] nospadingwalls.py
- [x] fbpatch.py (inlined in #232 )
- [x] nointelonwalls.py
- [x] spadenadefix.py
- [ ] aimbot2.py

Total confirmed to work: 51/53 (~91%)

Support dropped (a.k.a. nuked):
 * query.py
 * nosharp.py
 * platform.py (too large to port or maintain)
 * commandhelp.py (broken :x:) (this should probably be part of piqueserver...) 
 * stats.py (is the server here still working?)

**Comment by godwhoa** [comment]
Any Tracebacks from those crashes?

**Comment by NotAFile** [comment]
Airstrike should work, at least that's the command I always used to test things.

**Comment by NotAFile** [comment]
Script testing checklist:

 - [ ] afk.py
 - [ ] aimbot2.py
 - [ ] airstrike2.py
 - [ ] antijerk.py
 - [ ] arena.py
 - [ ] autohelp.py
 - [ ] babel.py
 - [ ] babel_script.py
 - [ ] badmin.py
 - [ ] blockinfo.py
 - [ ] commandhelp.py
 - [ ] daycycle.py
 - [ ] demolitionman.py
 - [ ] dirtnade.py
 - [ ] disco.py
 - [ ] fbpatch.py
 - [ ] flagreturn.py
 - [ ] freeforall.py
 - [ ] geoip.py
 - [ ] grownade.py
 - [ ] infiltration.py
 - [ ] map_extensions.py
 - [ ] mapmakingtools.py
 - [ ] markers.py
 - [ ] match.py
 - [ ] medkit.py
 - [ ] memcheck.py
 - [ ] minefield.py
 - [ ] nointelonwalls.py
 - [ ] nosharp.py
 - [ ] nospadingwalls.py
 - [ ] onectf.py
 - [ ] paint.py
 - [ ] passreload.py
 - [ ] platform.py
 - [ ] protect.py
 - [ ] push.py
 - [ ] query.py
 - [ ] rampage.py
 - [ ] rangedamage.py
 - [ ] rapid.py
 - [ ] ratio.py
 - [ ] rollback.py
 - [ ] runningman.py
 - [ ] savemap.py
 - [ ] smartnade.py
 - [ ] spadenadefix.py
 - [ ] spawn_protect.py
 - [ ] spectatorcontrol.py
 - [ ] squad.py
 - [ ] stats.py
 - [ ] strongblock.py
 - [ ] tdm.py
 - [ ] timedmute.py
 - [ ] tow.py
 - [ ] trusted.py
 - [ ] votekick.py
 - [ ] votemap.py
 - [ ] welcome.py
 - [ ] zoc.py

**Comment by swalladge** [comment]
`passreload` works but looks a bit hacky. Hopefully we can build this functionality into piqueserver during porting to the new config management later on.

**Comment by swalladge** [comment]
I just noticed this traceback with the push gamemode:

```
2017-12-26 17:13:04+1030 [-] Unhandled error in Deferred:
2017-12-26 17:13:04+1030 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
            self.mainLoop()
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
            self.runUntilCurrent()
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/piqueserver-0.1.0.post2-py3.6-linux-x86_64.egg/piqueserver/scripts/push.py", line 340, in check_intel_locations
            reset_intel(self, self.blue_team)
          File "/home/samuel/projects/piqueserver/venv/lib/python3.6/site-packages/piqueserver-0.1.0.post2-py3.6-linux-x86_64.egg/piqueserver/scripts/push.py", line 95, in reset_intel
            team.flag.set(*pos)  # If spawn not set, it would throw error.
        builtins.UnboundLocalError: local variable 'pos' referenced before assignment

```

**Comment by NotAFile** [comment]
this is caused by not having the correct metadata for the map, I'm pretty sure. Could be made a lot less cryptic though.

**Comment by swalladge** [comment]
Testing badmin now - it's at least semi broken. stay tuned

**Comment by NotAFile** [comment]
This is probably the issue with the most person-hours put into it right now...

**Comment by NotAFile** [comment]
@dgadelha Yes, that's a mistake. It might be added back in later, of course.
