### ISSUE TITLE
Port to ipaddress module, which is in the standard library in python3

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#126]
Currently, the google ipaddr module is used for IP bans, but python3 contains an `ipaddress` module in the standard library and 2.7 backports are available

**Comment by godwhoa** [comment]
Port on [ipaddress-port](https://github.com/piqueserver/piqueserver/tree/ipaddress-port) branch.
Only tested it with some unit tests and /ban command. Will test with range bans then merge.

**Comment by NotAFile** [comment]
I'll make a PR so we can discuss the changes

**Comment by NotAFile** [comment]
closed by #134
