### ISSUE TITLE
Add admin_only kwarg to command

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#128]
this allows you to decorate a function with @command("name", admin_only=True)

**Comment by godwhoa** [comment]
If readability is the intent ` @restrict("admin", "guard")` is fine IMO.

**Comment by NotAFile** [comment]
well, the whole @restrict thing is a bit of a mistake... since server owners can configure what commands require what rights, the only restriction that makes sense is the admin/superuser restriction.

**Comment by godwhoa** [comment]
Closed with #156
