### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#13]
Currently, spades-server has no own icon.

Having one would be nice :)

**Comment by noway421** [comment]
![ss](https://cloud.githubusercontent.com/assets/2031472/21576192/6f6faf24-cf8b-11e6-978c-b7005aaab153.png)

brainstorming

**Comment by feikname** [comment]
Whoa there, that was unexpected!

I enjoyed the concept you made a lot :grinning:

**Comment by noway421** [comment]
<img width="367" alt="screen shot 2017-01-13 at 3 42 42 am" src="https://cloud.githubusercontent.com/assets/2031472/21894018/88a1e226-d942-11e6-92c3-1d2376bac3cc.png">

**Comment by feikname** [comment]
Found as 512x512 SVG with *CC 3.0 Unported* license [here].

**Comment by noway421** [comment]
LGTM

**Comment by feikname** [comment]
And an SVG spade suit [here](https://thenounproject.com/term/spade/286772/). 

Seems like all left is to centralize and submit the icon.

**Comment by kmsiapps** [comment]
How about this?

Used these images : 
http://goo.gl/1JHNwc
https://commons.wikimedia.org/wiki/File:Ic_cloud_queue_48px.svg

![icon](https://cloud.githubusercontent.com/assets/23615360/22180414/5686d13e-e0b3-11e6-8421-2e1a91711de0.png)

**Comment by feikname** [comment]
@kmsiapps Nice!

Although I think everything in blue is a bit weird, but maybe that just me.

**Comment by noway421** [comment]
@kmsiapps This is awesome! This is exactly something we should be going with!!

**Comment by noway421** [comment]
I'm going trace it to svg and /maybe/ add some alterations, are you ok with that @kmsiapps ?

**Comment by kmsiapps** [comment]
@noway421 Sure!

**Comment by feikname** [comment]
The cloud icon is [CC 4.0 attribution international](https://creativecommons.org/licenses/by/4.0/deed.en), but I'm not sure where we should mention it. 

'README.md' maybe?

**Comment by kmsiapps** [comment]
@feikname Maybe we would replace the cloud icon.
Using this one seems good : goo.gl/6Xgqab

**Comment by kmsiapps** [comment]
@feikname We can replace the cloud icon with this : goo.gl/6Xgqab

**Comment by feikname** [comment]
@kmsiapps Thanks!

**Comment by noway421** [comment]
Traced kmsiapps's logo. Also couldn't resist to.. change the color!

![logo](https://cloud.githubusercontent.com/assets/2031472/22181361/cc7f76b6-e0ef-11e6-95eb-dd172fc43c47.png)

Also looks good on all sizes, even 16x16!

<img width="294" alt="screen shot 2017-01-22 at 10 16 16 pm" src="https://cloud.githubusercontent.com/assets/2031472/22181401/75798af4-e0f0-11e6-8018-0ed9ca9b525e.png">

What do you guys think?

[logo.svg.zip](https://github.com/piqueserver/piqueserver/files/721825/logo.svg.zip)

**Comment by kmsiapps** [comment]
@noway421 Much better. Great work!

**Comment by feikname** [comment]
It look gorgeous!

However, it still seems like something is off to me. Can you please change the border color a couple of times and publish the results? :thinking:

**Comment by noway421** [comment]
Hope that helps!

<img alt="screen shot 2017-01-22 at 10 26 51 pm" src="https://cloud.githubusercontent.com/assets/2031472/22181458/f2f5d860-e0f1-11e6-8008-594be235c3db.png">

**Comment by feikname** [comment]
I like more this one:
![image](https://cloud.githubusercontent.com/assets/4926869/22181540/c0dba610-e075-11e6-9d72-87932be0fdaf.png)

**Comment by noway421** [comment]
Yep, liking it too!

**Comment by noway421** [comment]
went full material and added cloud shade too

![logo](https://cloud.githubusercontent.com/assets/2031472/22182418/da7cdf14-e109-11e6-94e4-046a7065236e.png)
[logo.svg 2.zip](https://github.com/piqueserver/piqueserver/files/721919/logo.svg.2.zip)

**Comment by NotAFile** [comment]
looks great!

**Comment by feikname** [comment]
So, is the above image going to be our icon?

@NotAFile @noway421 @swalladge

**Comment by noway421** [comment]
I vote yes

**Comment by swalladge** [comment]
Looks good to me.

**Comment by feikname** [comment]
I vote yes too.

**Comment by feikname** [comment]
I set it the organization icon.

If anyone wants to add it in the `README.md`, feel free to open a pull request.
