### ISSUE TITLE
Reduce size of commands.py

### ISSUE THREAD

**Issue by godwhoa** [piqueserver/piqueserver#146]
Currently commands.py is too large which makes it harder to maintain.

### LoC Breakdown
Command System: ~330 LoC
Core Commands(eg. /ban, /login etc.): ~1095 LoC
Total: 1428 LoC

### Possible solutions:
- make a core commands submodule 
- split them into scripts

**Comment by NotAFile** [comment]
I disagree with making core commands scripts

**Comment by godwhoa** [comment]
Yeah that sounds better and gives a good starting ground. I'll extract out the exotic ones into scripts.
