### ISSUE TITLE
Explore the possibility of adding Deploy to Azure button

### ISSUE THREAD

**Issue by noway** [piqueserver/piqueserver#15]
http://www.bradygaster.com/post/the-deploy-to-azure-button
https://apievangelist.com/2016/09/12/where-is-the-deploy-to-aws-and-google-button/

I.e. something like this:
[![Deploy to Azure](http://azuredeploy.net/deploybutton.png)]()

**Comment by feikname** [comment]
It's a interesting idea, which certainly would make deploying servers a bit easier.

I don't know what the web interface does already, but adding administration purposes to it if it doesn't sounds like a good thing to do together with this.

**Comment by swalladge** [comment]
Just to add: Heroku would be another good option to support for a 'Deploy to Heroku' button

**Comment by noway421** [comment]
Web interface shows only server statistics right now. Full on administration would be quite a big thing to implement, definitely will go into another issue (if it has that much purpose/need anyway). But it is true that it would bring it from bare-bones distribution to a somewhat full package with complete set of utilities.

@swalladge unfortunately heroku doesn't support udp port exposure, so it wouldn't be possible to connect to the server

Also docker cloud has another such button: https://docs.docker.com/docker-cloud/apps/deploy-to-cloud-btn/

**Comment by NotAFile** [comment]
Is this really something we want? With docker, this is essentially redundant, I feel. But some quicker way of deploying would indeed be nice.

**Comment by swalladge** [comment]
Agreed. 'one click server' could also be something that some third party website could provide.

**Comment by noway** [comment]
I think we want it. "Deploy to Azure", "Deploy to AWS", "Deploy to GCP". This would greatly reduce the barrier of entry to roll out your own piqueserver.

Docker is just one step in this. And for azure/aws/gcp we still might to right custom deployment scripts.

Idk, very low on priority list. A nice-to-have.

**Comment by feikname** [comment]
I will reopen this as a "nice-to-have". Added the low-priority label.

**Comment by NotAFile** [comment]
I think I'll close this after all. It would be nice, but doesn't really need to be done by us.
