### ISSUE TITLE
Refactor out script logic

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#166]
The script logic is currently just jammed into server.py, it would be nice to move it out into another file

**Comment by pythonpsycho1337** [comment]
Hi

Me, Alberto (mentioned above) and 3 other people want to grab this task. We forked the repo as we did not have permission to create and work on a branch on this one. 

Also, we are available in the discord channel for this project :)

**Comment by pythonpsycho1337** [comment]
If we have time, we will try to take a look at #436 as well

**Comment by pythonpsycho1337** [comment]
When doing a "find . -name server.py" I get these files: 
```
./piqueserver/server.py
./piqueserver/core_commands/server.py
./pyspades/server.py
```
Which of these one is it that we should refactor? 
I suppose that you mean ./piqueserver/server.py?

**Comment by NotAFile** [comment]
yep, that's the one I mean

**Comment by pythonpsycho1337** [comment]
Okay! 

And by script logic you mean that these functions:
```
check_scripts(scripts)
validate_team_name(name)
sleep(secs)
ensure_dir_exists(filename: str)
random_choice_cycle(choices)
```
And these classes:
```
FeatureTeam(Team)
EndCall(object)
FeatureProtocol(ServerProtocol)
```
should be moved to other files? (Or is there something else that should be moved)

**Comment by NotAFile** [comment]
"script logic" is a bad title here. what I actually mean is the extension/plugin logic. This includes check_scripts, but the rest is jammed into the main function in that file. This is one of the ugliest parts of piqueserver, so I might have to write you a small doc on how it works.

**Comment by pythonpsycho1337** [comment]
Ah ok, I think I get it :) 

This is the chunk of code you are talking about in the main function(run) that should be refactored in addition to the check_scripts funtion:
```
# apply scripts

    protocol_class = FeatureProtocol
    connection_class = FeatureConnection

    script_objects = []
    script_names = scripts_option.get()
    script_dir = os.path.join(config.config_dir, 'scripts/')

    for script in script_names[:]:
        try:
            # this finds and loads scripts directly from the script dir
            # no need for messing with sys.path
            f, filename, desc = imp.find_module(script, [script_dir])
            module = imp.load_module(
                'piqueserver_script_namespace_' + script, f, filename, desc)
            script_objects.append(module)
        except ImportError as e:
            # warning: this also catches import errors from inside the script
            # module it tried to load
            try:
                module = importlib.import_module(script)
                script_objects.append(module)
            except ImportError as e:
                log.error("(script '{}' not found: {!r})".format(script, e))
                script_names.remove(script)

    for script in script_objects:
        protocol_class, connection_class = script.apply_script(
            protocol_class, connection_class, config.get_dict())

    # apply the game_mode script
    if game_mode.get() not in ('ctf', 'tc'):
        # must be a script with this game mode
        module = None
        try:
            game_mode_dir = os.path.join(config.config_dir, 'game_modes/')
            f, filename, desc = imp.find_module(
                game_mode.get(), [game_mode_dir])
            module = imp.load_module(
                'piqueserver_gamemode_namespace_' + game_mode.get(), f, filename, desc)
        except ImportError as e:
            try:
                module = importlib.import_module(game_mode.get())
            except ImportError as e:
                log.error("(game_mode '%s' not found: %r)" %
                          (game_mode.get(), e))

        if module:
            protocol_class, connection_class = module.apply_script(
                protocol_class, connection_class, config.get_dict())
``` 

Right?

**Comment by NotAFile** [comment]
yes, that piece of pure filth

**Comment by pythonpsycho1337** [comment]
@NotAFile 
What are the scripts actually doing?
I assume it is some sort of extensions to the game, like adding new weapons or characters. Is this correct? 

Also, if we refactor these code chunks into a separate file, what should we name the file(We are thinking about naming it something like "script_logic.py")?

**Comment by NotAFile** [comment]
I've written a small doc on this, as promised: https://piqueserver.readthedocs.io/en/latest/architecture.html#extension-scripts

I was personally planning on calling this module `extensions.py`

**Comment by pythonpsycho1337** [comment]
Awesome! thanks! 

Alright, we will call it ```extensions.py``` then! :+1:
