### ISSUE TITLE
Create new packet instances instead of reusing the old ones

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#179]
This might cause subtle bugs in various places in the future

Allocation costs might be an issue, of course. But luckily, cython has the `@cython.freelist` decorator to make allocation blazingly fast.

**Comment by Svardl** [comment]
Hey, another KTH student group here. We're thinking about working on this issue. Could you point us to which files the issue concerns? It's not entirely clear. We found the pyspades/packet.pyx file, which seems relevant. Can we edit this file? We're unsure since it's in the pyspades directory.

**Comment by NotAFile** [comment]
So basically, here's what's going on. In the top of `pyspades/server.py` and `pyspades/client.py` you will find a number of singleton instances of loaders. They are created once and then used throughout the program. This is pretty much a premature otimisation and has lead to some questionable design decisions and errors. Some packets are being filled in partially in some places and the completed in others. This is pretty intransparent. Instead, these loaders should be instantiated when the packet is actually sent and discarded afterwards. Since this means more allocation which might slow things down, the effect of this change would need to be benchmarked. If it is a noticable change, it should be looked into if this can be mitigated by using cython's freelist feature, which can be used to speed up creating new objects.
