### ISSUE TITLE
Work with upstream pyenet

### ISSUE THREAD

**Issue by noway421** [piqueserver/piqueserver#19]
receiveCallback should be implemented there beforehand, which should be possible. Basically update our patches and submit them to their upstream

Corresponding issue in pyenet: https://github.com/aresch/pyenet/issues/1

**Comment by noway421** [comment]
`Socket.send` wrapper for `enet_socket_send` is missing too alongside the receiveCallback

**Comment by noway421** [comment]
Opened an issue there: https://github.com/aresch/pyenet/issues/3

**Comment by noway421** [comment]
their tests are failing on these pyspades changes... looks like the changes are breaking something in Host creation/deallocation.

dunno why is that

**Comment by noway421** [comment]
Socket.send and intercept callback are tested now. Waiting for upstream to comment/etc

**Comment by feikname** [comment]
Fixed in #21
