### ISSUE TITLE
The error message when IP_GETTER fails is cryptic

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#195]
Lets add error handling instead :)

Fallback handling would be nice too.

**Comment by NotAFile** [comment]
I generally feel like IP_GETTER is overused. There really is only one case where you actually care about fetching the public IP address:

LAN party: server address is host address
Server in data center: server address is host address
Private server behind NAT: server address is router address, IP_GETTER is needed.

So generally, we can disable the IP_GETTER in many cases. I think a message of this format would be nice:

#### host IP is public
```
The address of this server is aos://10298379:32887, master server registration is: On
```


#### host IP is private
```
The LAN address of this server is aos://10298379:32887, master server registration is: Off
The Public address of this server is aos://9128379:32887. NOTE: You probably need to enable port forwarding in your router so players outside of your network can join!
```

**Comment by swalladge** [comment]
Something that would make all this more transparent would be if everyone moved to using plain ip addresses instead of the bunch of random-looking numbers.
