### ISSUE TITLE
Improve command system

### ISSUE THREAD

**Issue by godwhoa** [piqueserver/piqueserver#199]
Areas to improve:
- ~Command parsing: Currently lot of commands index `args` without checking length so if player doesn't pass in right amount of args. it results in an exception. I suggest adding `arglen` kwarg to command decorator.~

- Help/Usage messages: Right now a command has to check if proper amount of arguments are passed in and print out usage message on it's own. Standardising this would be better for both devs. and players.

**Comment by NotAFile** [comment]
I disagree. The command system checks the length of the arguments of the function to see if the signature matches up.

Thus, in cases where the number of args is constant this is already implemented. The *args situation applies only to functions that can take a variable number of arguments. We can't do anything then, of course. If the function can take any number of arguments, we can't say anything about it and it has to decide for itself and raise e.g. a CommandError in case someone gets it wrong. There is just no way around that.

**Comment by NotAFile** [comment]
What we could however do of course is make commands that use *args unnecessarily use the proper method of declaring the arguments in the function signature instead.

**Comment by godwhoa** [comment]
> I disagree. The command system already checks the length of the arguments of the function to see if the signature matches up.

Got it. Will strikeout Command parsing part.

**Comment by godwhoa** [comment]
I will closing this issue. Looks like we need to refactor the commands instead of command system itself.

**Comment by NotAFile** [comment]
Might as well strike out the second part too then, since that's also implemented already :)

Look at the bottom of the commands.py file
