### ISSUE TITLE
Pysnip as a module tidy ups before name change

### ISSUE THREAD

**Issue by noway421** [piqueserver/piqueserver#20]
1. [ ] gitignore parity with .dockerignore
2. [ ] scope sys.path for importing userscripts (using a phantom fs? override modules in global paths?)
4. [x] run.py main()
3. [x] PKGNAME= for easy setting of the name
1. [x] tidy up gitignore (`*.egg-info/` vs no-wildcard versions)

**Comment by noway421** [comment]
the command calls are all over the place in the import-time scope in run.py. might be not worth the hassle when __main__.py works so good and exists especially for that purpose

**Comment by noway421** [comment]
re scoping sys.path: http://stackoverflow.com/questions/41517006/different-sys-path-values-for-different-modules-within-the-same-process

**Comment by noway421** [comment]
`sys.path` is one for the whole process, not possible per module. Other options are really not that possible I think. 

What we can do is set the added directory which we are adding to sys.path the same priority as `.`, in that case it wouldn't possibly break? There's still a slim possibility it seems. 

It's all theoretical, and there's little chance someone would use common module names from pip and expecting them to load

**Comment by feikname** [comment]
@noway421 It really seems unlikely someone use a pip module name. There is still the possibility, but we can simply issue an warning on the future wiki page for scripting, so this is not much of a problem.

I thinks its safe to add it with the same priority as `.`.

**Comment by noway421** [comment]
Yep. 

Just for clarity for future readers, here's what I meant: 

What I meant is that if someone going to do `import map` from a userscript, piqueserver wouldn't be able to favour https://pypi.python.org/pypi/map if it is installed in the system, but rather would always load pyspades.map from the piqueserver package. 

It is an undesirable behaviour, but not many people use such an edge case.

Actually, just had a thought about it. What if instead of changing sys.path, change the `.`? I.e. the the current working directory. That's something I haven't thought about, but it might actually work. Hopefully python allows cd'ing into python's egg content. Maybe not, but worth a try.

**Comment by feikname** [comment]
@noway421 Can this issue be closed?
