### ISSUE TITLE
Replace pyspades color module with builtin colorsys module

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#208]

**Comment by swalladge** [comment]
This isn't fully possible since colorsys doesn't provide the `interpolate*` functions.

**Comment by NotAFile** [comment]
Yes, true. The `color` package looks great if we want to be able to use color names, since we would need to add a dependency for that anyway...

**Comment by swalladge** [comment]
@NotAFile this appears to have been fixed as far as possible in https://github.com/piqueserver/piqueserver/commit/7a8ddc9a500b70426e9c188f9a52514e2037f3ef . Ok to close?
