### ISSUE TITLE
IP_GETTER fails on Windows if using https

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#215]

**Comment by NotAFile** [comment]
This is caused by lack of Twisted support for certificate validation on Windows.

https://twistedmatrix.com/trac/ticket/9209#ticket

Temporary workaround would be to make it use http if on windows instead

**Comment by swalladge** [comment]
Can we simply make `IP_GETTER` configurable from the `config.json`? This would solve both this and the issue where `services.buildandshootcom` is down/inaccessible

**Comment by swalladge** [comment]
(or even a list in the config so it can iterate through until one works)

**Comment by NotAFile** [comment]
I'm going to close this since I assume this was fixed by the aiohttp switch.
