### ISSUE TITLE
Rollback fills the insides with Black, not brown

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#221]

**Comment by 1AmYF** [comment]
The script has a constant on how to deal with non-surface-colors:

https://github.com/piqueserver/piqueserver/blob/5ef52df6051ff392fdc55c70ce44219ba8091f65/piqueserver/scripts/rollback.py#L52

However i personally wouldn't change anything about it. You will only see the black blocks if you were on the server during the rollback, as your client only then gets all the color data from the added non-surface-blocks. If you connect to the server after the rollback, the black blocks will be normally brown/dirt again, as you have newly loaded the vxl file.

**Comment by lokka30** [comment]
Should we adjust this value to be brown?

**Comment by NotAFile** [comment]
Sure, it's not like anyone really uses this script anyway though.
