### ISSUE TITLE
Support dynamic loading of scripts and gamemodes

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#222]
This would be helpful for faster debugging/testing of scripts. May or may not be complex to implement.

**Comment by NotAFile** [comment]
With the current system is is borderline impossible... :/

**Comment by NotAFile** [comment]
I thought I'd just elaborate on my plans here: I'd like to add shim classes that pretend to be Protocol and Connection objects, but expose a well-defined API instead. This means that plugins won't be able to do everything anymore, we have to manually place hooks in the places where we want plugins to hook into, but it does allow us to get rid of the subclassing stuff internally without breaking compatibility.
