### ISSUE TITLE
Update setup.py metadata

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#228]
Classifiers, etc. - none of these have been looked at much for a long time. Need to update them to reflect recent changes so we have correct info displayed on Pypi when we release 0.1.1

**Comment by feikname** [comment]
Just a side note, `piqueserver/cfg.py` also has to be updated to use `0.1.1`

**Comment by NotAFile** [comment]
We should really be using the standard __version__ attribute. We can also use setuptools to get the currently installed version of the module

**Comment by NotAFile** [comment]
related: #169

**Comment by swalladge** [comment]
Fixed in #230
