### ISSUE TITLE
Shutil copytree fails if the directory already exists

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#241]
There appears to be no way to get around this without basically rewriting it.

https://stackoverflow.com/questions/1868714

**Comment by godwhoa** [comment]
What type of behaviour do we want? merge src and dst, over-write dst with src or skip copytree if it already exists?

**Comment by NotAFile** [comment]
I guess merge and keep original files would be best? That way it's harder to accidentally delete your config etc.
