### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#27]
This is a low-priority longer-term goal, but it would be nice to move pique to a Python3, and maybe even replace twisted asyncio

**Comment by noway421** [comment]
We are reliant on twisted and pyenet for the core functionality. Pyenet is py3k already.

Twisted had some good progress on that matter in the previous 2 years. Here's their progress tracking: https://twistedmatrix.com/trac/milestone/Python-3.x

Looks like now's the moment we can consider looking into it.

**Comment by NotAFile** [comment]
Yes, last time I looked into this twisted was the blocker. I've already forked and started working locally. It would be great if all of the `from __future__ import x` declarations were added for all new files, that would probably speed up progress too.

**Comment by feikname** [comment]
Work-in-progress pull request: #50

**Comment by NotAFile** [comment]
The biggest issue seems to be `bytes` vs `str` vs `unicode`. Since the original code uses `str` for bytes, this was the major way python3 blew up. Since we don't have tests I would recommend slowly moving stuff that should be `bytes` away from `str`. An good place to start would be bytes.pyx and the ByteWriter and ByteReader classes.
