### ISSUE TITLE
Kick players whose name start with #

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#3]
The text below is left for historical purposes, please consider only the issue title.

----

Voting with player names is unreliable, permitting only votekicks by ID is better.

Reasons why:
* There can be duplicate names, how is the votekick script supposed to deal with that?
* Names can start with #, which prevents the default votekick script from kicking them.

This applies to every other command involving other players.

**Comment by noway421** [comment]
1. An option to solve this is to kick players with nicknames which are starting with # 
2. Duplicate names are fine to be undefined behaviour because it is always possible to identify them by id considering 1. is implemented
