### ISSUE TITLE
port wiki documents to docs

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#317]
Now that we have documentation with sphinx, it would make sense to port the github wiki pages and integrate them with the rest of the docs.

Advantages:

- all docs in single location
- no dependency on github
- more discoverable (especially if we make the docs become the official website or part thereof)
- easier to keep in sync with repo code

Disadvantages:

- more difficult to edit than github wiki

**Comment by NotAFile** [comment]
we should think about what pages we want to create in the wiki now... Things that actually make sense there, like lists of Plugins and external resources.
