### ISSUE TITLE
Expand use of logging

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#32]
Currently, everything is just naively `print`ed to stdout. It would be nice to use the `logging` module instead.

**Comment by feikname** [comment]
Agreed.

**Comment by NotAFile** [comment]
Piqueserver is already using twisted's logging facilities, however print is still used in some places where it should not be.

**Comment by godwhoa** [comment]
Can this be closed now?

**Comment by NotAFile** [comment]
sure
