### ISSUE TITLE
consider implementing the 1.x HELLOLAN packet

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#352]
Could pretty much almost just be copied over from the ace.py code. Would anyone use it? probably not.

https://github.com/piqueserver/aosprotocol/issues/18

**Comment by xtreme8000** [comment]
BetterSpades will use it once I figured out how to use the C socket API on `win`

**Comment by NotAFile** [comment]
Perhaps we should support enet with it too... shouldn't be too hard to add
