### ISSUE TITLE
Changing gamemodes requires a restart

### ISSUE THREAD

**Issue by StripedMonkey** [piqueserver/piqueserver#353]
This really should be done dynamically, even if there is an initial one.
On the surface this would be pretty easy to do, but, the problem with this is that a lot of maps have a restriction on what gamemodes they can be played in. A prime example being that most maps designed for arena will fail utterly when played on ctf.

**Comment by NotAFile** [comment]
This is currently not possible, unfortunately. Internally, scripts and gamemodes are the same thing, and applying scripts requires recreating the `Protocol` "God Class" that nearly all of the state is stored in, which implies disconnecting all players. But I have a half-finished version of a new gamemode interface sitting in a git branch that should fix this.

**Comment by NotAFile** [comment]
closing in favor of #222, since it is essentially the same issue, just with gamemodes
