### ISSUE TITLE
Add progress bar while downloading ENet in setup.py

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#36]
As mentioned by @NotAFile in #35, converting ENet download to inside setup.py removed the progress bar. Its a nice little feature that should be re-added sometime.

**Comment by kmsiapps** [comment]
It was added at https://github.com/piqueserver/piqueserver/commit/f28703bb8ca871aa52bd4c91c13ff0f2c30ea5a9, I suppose.
