### ISSUE TITLE
someway for prevent server shutdown (cuz cheaters?)

### ISSUE THREAD

**Issue by MikkelDK** [piqueserver/piqueserver#366]
Hello.. as the title say.

is there someway possible for prevent server to be shutdown/crashed by cheater/hackers? ^^

**Comment by NotAFile** [comment]
you should be running piqueserver with a process supervisor like systemd, supervisord, daemontools, dockerd etc. That way if a crash occurs, the server will be instantly restarted.

Please make sure to report any specific crashes (with traceback) here so that we can fix them.

**Comment by NotAFile** [comment]
closing this, feel free to open another issue if you find some crashes!
