### ISSUE TITLE
Make dependency restrictions less strict

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#40]
Currently the restrictions are very tight in the `requirements.txt` and `setup.py`, which makes it difficult to install using packages from linux repositories. For example, packages in the Arch repos are generally newer versions than those in some other distros.

What needs to be done is to determine the earliest and most recent versions of dependencies it can run well with and set those as restrictions instead.

**Comment by feikname** [comment]
Fixed in #40
