### ISSUE TITLE
streamline getting example configuration

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#41]
Currently you must clone the repository to get example config from the `configs` directory to be able to actually run the server. This process needs to be streamlined to remove this step.

What I'm thinking for implementing this:

- store example configs somewhere like in `feature_server` to be copied into the module/package
- add a cli argument like `--copy-config` to copy the default configuration to `~/.piqueserver/` or a custom location
- make sure the server knows the default location to read configuration from - it should be the dot directory in the user's home directory - don't simply use the example config silently as installed from the package (security risk)

**Comment by NotAFile** [comment]
I'd much prefer for the configs to live in XDG_CONFIG_DIR, (aka `.config/`). This makes it easier to structure the configs and plugins, plus it doesn't litter the home dir with one more file. Ideally, to allow system-wide installation, you'd use a config override system like many other applications do, by checking many places in a predetermined order and either extending or replacing the given config if one is found later in the list. Extending sounds like a config-debugging nightmare, so replace is probably best.

 - /etc/piqueserver
 - $XDG_CONFIG_DIR/piqueserver
 - `-d` option

**Comment by noway421** [comment]
`$XDG_CONFIG_DIR/piqueserver/` sounds like a plan with defaulting to ~/.config/piqueserver is XDG is not set up

**Comment by swalladge** [comment]
I'm not convinced by using `/etc/piqueserver` at all. The config directory needs read-write access currently (with the logs directory), and there is no good reason for running the server as root. Better to stick to user's home directory, with the `-d` override available.

**Comment by noway421** [comment]
split the access restrictions is a good idea though. read only stuff doesn't need r/w. 

maybe /var/log/piqueserver as the ultimate fallback? then up to the configuration chain, $CONFIG_DIR/logs as it is now. then $LOG_DIR if user has specified one? which could be -l flag

**Comment by feikname** [comment]
How about search the configuration directory in this order:

1. Check for `-d` option (if invalid, abort)
2. Check for `$PIQUESERVER_CONFIG_DIR` (if not empty and invalid, abort)
3. Default to `$XDG_CONFIG_DIR/piqueserver` (if has any permission issues, abort)

And do the same thing for log files:

1. Check for `-L` or `--logs` option (if invalid, abort)
2. Check for `$PIQUESERVER_LOG_DIR` (if not empty and invalid, abort)
3. Default to `CURRENT_CONFIG_DIR/logs` (if has any permission issues, abort logging)

**Comment by NotAFile** [comment]
@swallage putting configs and logs into system dirs is necessary to install piqueserver as a daemon for linux. In that case, piqueserver would be run as a user without a home directory so there is no other place to put the files.

This should be moved to a new issue as the original cause of this one was fixed

**Comment by swalladge** [comment]
@NotAFile yep this specific issue is resolved. I don't agree with the need to put configs/logs in system dirs for two reasons - 1. there's no reason why it couldn't be run as a user with it's own home directory (iirc every linux user has it's own home directory path set anyway), and 2. with the `-d` option you can simply set aside a directory owned by the piqueserver daemon user which you pass to the `-d` argument.

**Comment by NotAFile** [comment]
@swalladge System dirs is how this is done for all linux daemons and that means we probably should also do it that way if we want to be accepted by distro developers (not sure how picky they are). Really, I don't see a reason why we should be any different.

If the user has a home dir or not is relatively irellevant as my point stays: there is no other place to put these files. We don't want to litter /home with one more dir. /opt would probably work, but I have never seen /opt used by a debian package in the normal repos which probably means the developers don't like seeing it.
