### ISSUE TITLE
Improve /ban command UX

### ISSUE THREAD

**Issue by godwhoa** [piqueserver/piqueserver#416]
Currently ban command takes duration in minutes which gets annoying if you want to ban for 1 week etc.
The command looks like this `/ban <player> [duration] [reason]` we can keep the interface as is but do the duration parsing differently. 
`/ban #1 10080 ab` If duration is all digits we treat them as minutes. (like we currently do)
`/ban #1 1w ab` if it is not all digits we pass it to [pytimeparse](https://github.com/godwhoa/pytimeparse)

**Comment by swalladge** [comment]
Sounds great! Could we implement a simpler version of pytimeparse within piqueserver to avoid requiring another dependency?

**Comment by godwhoa** [comment]
@swalladge pytimeparse itself is 181LoC(ignoring tests/packaging) we could vendor it if we want. It'll also be used for #330.
