### ISSUE TITLE
Players Can Increase Health, Grenades, and Blocks Arbitrarily

### ISSUE THREAD

**Issue by 0verk1ll** [piqueserver/piqueserver#422]
By editing **Player.cpp** in openspades, players can arbitrarily increase their health, grenade count, and block count.

```
/* default health 100 */
health = 500;
/* default grenades 3*/
grenades = 500;
/* default blockStocks 50 */
blockStocks = 500;
```

I made the above changes and recompiled openspades.

The servers I tested on could detect the change to health and acted as if I only had 100 health.

The servers I tested on allowed me to place 55 blocks, but no more. I should only be allowed to place 50 blocks.

All but one server I tested on allowed me to use as many grenades as I wanted.

Is there a way to prevent people from cheating like this? I also post [this issue to openspades](https://github.com/yvt/openspades/issues/795).

**Comment by NotAFile** [comment]
Health, block count etc. are already tracked server-side. Your client might think it has 10000000 health, but the server knows you don't and will track your health properly. Even if you can throw infinite grenades, you will spot that these grenades don't actually appear or explode for other players.

There are some servers with very, very, very old software out there, so you shouldn't be surprised to have the ability to do some bad things on some of them. In that case, you should try to contact the server admins and convince them to upgrade.

**Comment by feikname** [comment]
I think it's worth checking if the 55 block issue affects piqueserver

**Comment by xtreme8000** [comment]
I think its there to prevent desync issues from appearing to the player.
