### ISSUE TITLE
[Enhancement] Use Ranged Weapons and Blocks for Melee Attack

### ISSUE THREAD

**Issue by 0verk1ll** [piqueserver/piqueserver#425]
If a player is surprised, by an enemy at close range, they should be able to use whatever is in their hand as a melee weapon. For example, I should be able to strike an enemy with a block, grenade, or the stock of my gun using the secondary attack button. These melee attacks should do less damage than the spade, but would make for more interesting and realistic game-play.

**Comment by lokka30** [comment]
I think that takes away part of the strategy of being surprised by the enemy when you have blocks out.
Grenades can already be cooked and thrown to convert a situation into a trade kill quite easily.
