### ISSUE TITLE
[Bug] Unable to Throw Grenade while Running

### ISSUE THREAD

**Issue by 0verk1ll** [piqueserver/piqueserver#428]
While a player is running, they are unable to throw a grenade. This is very frustrating as someone could do so in real life. A player should be able to throw while running, but have reduced range and decreased accuracy.

p.s. Being unable to shoot a gun while running makes sense.

**Comment by 0verk1ll** [comment]
I have only tested on OpenSpades. I assumed this would be a server issue.

**Comment by NotAFile** [comment]
nope, this is currently a client decision

**Comment by feikname** [comment]
Can anyone check if this happens on classic? If so I can see why BetterSpades and OpenSpades would want to replicate the behaviour so as to not provide advantages over the original client.

**Comment by NotAFile** [comment]
Since this is intended behavior, I am closing this issue as it is not a bug. If this behavior should be allowed in the future is a question for another day.
