### ISSUE TITLE
Use setuptools_scm

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#445]
While writing an issue template, I noticed that any currently installed version still reports itself as 0.1.3, even though it's the current master version. setuptools_scm can solve this by automatically generating a current version from the git tag. For example, mine is currently `0.1.4.dev269+g61530fb.d20190121`, because I'm after 0.1.3, 269 commits ahead, on git commit 61530fb and I have uncommited changes made on 2019-01-21. This is very useful for bug reports from people installing from git and also means we will never need to manually set the version again. (to clarify, it only adds the long stuff if necessary; if I was on the tag 0.1.3 exactly, 0.1.3 would be the version it generates.

**Comment by utf-4096** [comment]
Superseded by #786, which aims to use setuptools-scm.
