### ISSUE TITLE
Grenades don't damage the map

### ISSUE THREAD

**Issue by vinceshores** [piqueserver/piqueserver#449]
Currently, grenades will not damage the map when they explode. They do damage the player as expected.

**Comment by NotAFile** [comment]
what is the version and installation method?

**Comment by vinceshores** [comment]
Just upgraded to the latest (422c49c1efe482b6e8783aa496d837d82556cec4) with
`pip install git+https://github.com/piqueserver/piqueserver.git --upgrade`

**Comment by godwhoa** [comment]
I can't reproduce it. Can you share the config and any custom scripts you might be using?

**Comment by NotAFile** [comment]
Does this keep happening if you:

 - remove all third party scripts?
 - remove all official scripts?

Do you receive damage from grenades? What appear in the console (with `log_level=debug`) when throwing grenades? Do your grenades appear for other players?

**Comment by vinceshores** [comment]
Actually this is my bad. I thought I had overwritten the config and removed all scripts but I had written to the wrong directory. Grenades are currently working.
