### ISSUE TITLE
Advancing map to "random" or "classicgen" disconnects players

### ISSUE THREAD

**Issue by jellopudding** [piqueserver/piqueserver#452]
**Describe the bug**
In setting up a server on my RaspberryPi I encountered a bug where forcing the map to advance to either "random" or "classicgen" will cause me to disconnect. I've tried this with Openspades 0.1.3 and voxlap 0.75 with the same results.

**To Reproduce**
1. Join Server
2. login as admin/mod
3. Run /map random or /map classicgen
4. Run /advancemap
5. Wait for map to generate

Eventually you stop interacting with the rest of the environment before Openspades returns to the server browser because of a DC for an "Unknown Reason" and the voxlap client will just close.

**Expected behavior**
The player should retain connection to the server during transition to a random or classicgen map.

**Stack Trace**
No error message is logged or outputted to console from the server, however Openspades logs do detail the client side of the disconnect. https://pastebin.com/gWLuDBMc
Near the bottom I pasted what little the server output.

**Server:**
 - OS/Version: Raspbian 9.6
 - Piqueserver Version: linux 0.1.3, installed through pip

**Clients:**
 - Name: Openspades, Voxlap
 - Version: 0.1.3, 0.75

**Additional context**
This issue doesn't seem to occur with maps loading from a `.vxl` file.
I noticed that piqueserver reports the disconnect several seconds after Openspades throws it's first `Disconnected because of error` which occurs just a second before the server reports that the map loaded successfully.
No additional Scripts were loaded and game mode is CTF.

**Comment by godwhoa** [comment]
First off thanks for the detailed bug report. But I couldn't reproduce it locally(v0.1.3, linux, amd64, python 3).

**Comment by godwhoa** [comment]
Tried with python 2 as well works fine.

**Comment by jellopudding** [comment]
I installed piqueserver via `pip3 install piqueserver` so it should be using python3.5 at least. I can try the current master but I have some suspicion that there might be some miscommunication between the client and server so I'll set up wireshark to log the packets with the current release beforehand. I also seem to remember getting disconnected from that one public piqueserver hosted on a raspberry pi in Australia as well and I'll make sure to double check that later too.

**Comment by jellopudding** [comment]
I tried installing from the git repo but it exits with this error: `Could not find a version that satisfies the requirement Pillow<6,>=5.1.0 (from piqueserver==0.1.3) (from versions: )`

**Comment by jellopudding** [comment]
I'm getting disconnected with the git version as well, log is the same too.

**Comment by godwhoa** [comment]
> I also seem to remember getting disconnected from that one public piqueserver hosted on a raspberry pi in Australia as well and I'll make sure to double check that later too.

Is it this one? aos://388381909:25565:0.75 IIRC, it crashes openspades with some zdepth error. Wanted to reproduce that one as well but couldn't. It's hosted by @bieito98 

I currently don't own a Raspberry pi but maybe others can try and reproduce it.

**Comment by jellopudding** [comment]
I'm having issues with installing dependencies for pysnip, Pillow for python2 is specifically giving me a hard time. I'll get back to you as soon as I can get pysnip running.

**Comment by NotAFile** [comment]
protip, don't bother with python2

**Comment by godwhoa** [comment]
Small update, finally got myself an Raspberry Pi and I can reproduce it.
@NotAFile  As far as tests go, they all pass.
```
(piqueserver) pi@raspberrypi:~/piqueserver $ pytest
========================================================= test session starts ==========================================================
platform linux -- Python 3.5.3, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/pi/piqueserver, inifile:
plugins: cov-2.6.1
collected 69 items                                                                                                                     

tests/piqueserver/test_ban_pubsub.py .                                                                                           [  1%]
tests/piqueserver/test_commands.py ....                                                                                          [  7%]
tests/piqueserver/test_config.py ............                                                                                    [ 24%]
tests/piqueserver/test_core_commands.py .                                                                                        [ 26%]
tests/piqueserver/test_networkdict.py .........                                                                                  [ 39%]
tests/piqueserver/test_player.py .                                                                                               [ 40%]
tests/piqueserver/test_run.py ....                                                                                               [ 46%]
tests/piqueserver/test_server.py ..                                                                                              [ 49%]
tests/piqueserver/test_statistics.py ..                                                                                          [ 52%]
tests/piqueserver/test_statusserver.py .                                                                                         [ 53%]
tests/pyspades/test_bytes.py .....                                                                                               [ 60%]
tests/pyspades/test_color.py ....                                                                                                [ 66%]
tests/pyspades/test_common.py .........                                                                                          [ 79%]
tests/pyspades/test_constants.py .                                                                                               [ 81%]
tests/pyspades/test_mapgenerator.py .                                                                                            [ 82%]
tests/pyspades/test_player.py ..                                                                                                 [ 85%]
tests/pyspades/test_protocol.py .                                                                                                [ 86%]
tests/pyspades/test_server.py .                                                                                                  [ 88%]
tests/pyspades/test_types.py ........                                                                                            [100%]

====================================================== 69 passed in 6.29 seconds =======================================================
(piqueserver) pi@raspberrypi:~/piqueserver $
```

**Comment by NotAFile** [comment]
does it only happen with advancemap, or also with normal rotations? I'd be surprised if not, but that would narrow it down quite a bit.
