### ISSUE TITLE
Right-clicking in distance disabled block building

### ISSUE THREAD

**Issue by vinceshores** [piqueserver/piqueserver#454]
**Describe the bug**
The script fbpatch.py was merged into the main player.py at some point. It prevents a line building bug that allowed building lines from anywhere you have line of site. Anytime the mouse is right-clicked, if the distance two the nearest block is greater than 6 line building is disabled by setting `connection.can_complete_line_build`, as the player could not have started a valid line build. On line building, `connection._can_build` is used to check for this to see if the line can be built. When this got merged however, this check was also used for `on_block_build`. So that if you right click off in the distance you can no longer build with left click until you right click nearby again.

**To Reproduce**
1. Join Game
2. Right click far away on map or the sky
3. Cannot build blocks with left click until right clicking on nearby blocks again

**Server:**
 - Piqueserver Version: 0.1.3 (fcd45b2c37fbbdf669b384d2a4e9e7b159316b96)

**Comment by godwhoa** [comment]
Fixed with #464.
