### ISSUE TITLE
Use pyenet as a package

### ISSUE THREAD

**Issue by noway** [piqueserver/piqueserver#46]
Currently in the process of getting the Mat's changes into pyenet upstream. Once that done, there are at least 1 bug to fix

That will narrow down the diff change count to maybe couple of lines.

**Comment by noway421** [comment]
Update: https://github.com/aresch/pyenet/pull/7 for the changes. And the other PR in that repo is for the bug fix.

**Comment by NotAFile** [comment]
since aresch does not seem to be interested in maintaining pyenet, we might be forced to run our own fork.

**Comment by swalladge** [comment]
Update: our fork ( https://github.com/piqueserver/pyenet/ ) is now published to pypi and PR #99 should resolve this issue. We can sort out politics re maintainers later...
