### ISSUE TITLE
Merging of goto and move removes scenario where players are allowed to move themselves but not others

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#474]
previously, by granting `goto` but not `move`, it was possible to allow players to move only themselves on e.g. build servers. This is no longer possible.

**Comment by swalladge** [comment]
Currently rights are per-command granularity, so it doesn't look possible to conditionally allow using a different player arg to `move`. Perhaps the easiest method might be to add a command like `moveme`?

**Comment by NotAFile** [comment]
From memory, other commands already used checks against the roles the user was in, such as `trusted` with `/votekick`? I think what I was going for here was have a similar rule here, where the command has a built-in check that means only admins or users with a special role could move other players.
