### ISSUE TITLE
Client detection appears as 'Unknown'

### ISSUE THREAD

**Issue by Kuunikal** [piqueserver/piqueserver#482]
**Describe the bug**
Using the `/client <player>` command will show 'Unknown' for each of the values. 

**To Reproduce**
1. Run command  `/client <player>`
2. See `Player is connected with Unknown vUnknown on Unknown`

![image](https://user-images.githubusercontent.com/28056363/55524902-e1fdd700-565c-11e9-8940-97e0484802a4.png)

**Expected behavior**
It should show the client, client version, and operating system.

**Server**
 - OS/Version: Linux
 - Piqueserver Version: c86f894

**Client**
 - Name: Voxlap client

**Comment by NotAFile** [comment]
For Voxlap clients this is expected, since voxlap does not respond. We might want to add an "probably voxlap" message for that case, though.

**Comment by Kuunikal** [comment]
Oh, yeah. Looks like aloha's script is modified to show something different when running `/clin`.
Even the operating system wasn't reported, though.

**Comment by NotAFile** [comment]
yeah, it just guesses voxlap on windows if the client doesn't reply for a while.
