### ISSUE TITLE
Ban Subscribe appears to be broken

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#483]
**Describe the bug**
kuunikal says bansubscribe did not work for him

**Comment by Kuunikal** [comment]
To elaborate:

This is what I was putting in when uncommenting the line (censored the server and port):

```
urls = [ [ "http://sub.domain.com:#####" []]]
```

The list I tried subscribing to did NOT end in `/subscribe.json`. Also no idea what those empty brackets are, very spooky.

**Comment by swalladge** [comment]
@Kuunikal did you encounter #524 , or was this because of a missing comma between the url string and the filter whitelist array?
