### ISSUE TITLE
Team Join bug

### ISSUE THREAD

**Issue by Sonicscream** [piqueserver/piqueserver#502]
**Describe the bug**
Unable to join a team on several gamemodes but not all.

**To Reproduce**
Setup arena or tdm server.
Attempt joining a team.
(Try again for a new error)

**Expected behavior**
Expected to be able to join a team, but unable to... stuck at main menu.

**Stack Trace or logs**
https://pastebin.com/aTPeUW86

3rd line is from attempting to join a team a second time.

**Server (please complete the following information):**
 - OS/Version: Centos 7.6
 - Python Version: python3.6 from yum
 - Piqueserver Version: Installed from master 5/4/2019 @ ~12:00 AM est (git describe doesn't show anything)

**Client (if relevant)**
 - Name: OpenSpades
 - Version: 0.1.3

**Additional context**
Tested arena, tdm, onectf. Onectf was the only mode to work, the others exhibited this bug.
Tested with no scripts and on counter-strike maps. Team balance adjustment didn't seem to help, nor did turning off respawn waves.

**Comment by NotAFile** [comment]
Has removing the feature exchange fixed this?

**Comment by Sonicscream** [comment]
Yeah.

**Comment by NotAFile** [comment]
closing in favor of #504, which is the underlying issue
