### ISSUE TITLE
OpenSpades crashes when sent id 60 (extinfo) before end of map transfer

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#504]
**Describe the bug**
OpenSpades receiving ExtInfo confuses the heuristics it used to determine in versions 0.1.3 and before.

This is not our bug, but we need to work around this with existing openspades clients.

As OpenSpades <= 0.1.3 does not support ExtInfo anyway, we should only send ExtInfo when we have made sure that the client is not OpenSpades <= 0.1.3, not unconditionally.

**Comment by NotAFile** [comment]
See also https://github.com/yvt/openspades/issues/826 and the client fix in https://github.com/yvt/openspades/pull/825

**Comment by swalladge** [comment]
Can this be closed since #507 was merged? Or do we want more testing?

**Comment by NotAFile** [comment]
It has been working for new
