### ISSUE TITLE
Some commands crash when called through irc

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#510]
**Describe the bug**

Some commands use methods of the game/server connection that aren't implemented for the irc connection, such as `send_lines`. This causes the command to crash, a traceback in the logs, and no feedback to the irc user.

**To Reproduce**

1. get a server running with irc enabled
2. call `!help` (reproducible with other commands too) from the irc channel
3. view logs

**Expected behavior**

for commands that should be available through irc: no crash

for commands that require to be called in-game: be not allowed to call it, with a feedback message.

**Comment by NotAFile** [comment]
This bug was fixed for console, but not for IRC in https://github.com/piqueserver/piqueserver/commit/dcc6af47068a2174af1eef22273add613d647cea

Seems like the solution can just be pretty much copy-pasted into irc.py.
