### ISSUE TITLE
bansubscribe urls format invalid in toml

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#524]
Toml only allows homogeneous lists, while the type is currently `[[str, list], [str, list]]`. It also doesn't seem to like tuples (otherwise `[(str, list)]` could be valid).

**To Reproduce**

Uncomment the example urls value in the config. See https://github.com/piqueserver/piqueserver/blob/894d8521c04ebd1db4be23043da0bc99df28f72e/piqueserver/config/config.toml#L217-L219

**Comment by swalladge** [comment]
Ah I just realized that implementing #519 would fix this.

**Comment by NotAFile** [comment]
It's good to note that this is a actually broken either way
