### ISSUE TITLE
CFLAGS - and thanks!!

### ISSUE THREAD

**Issue by roadapathy** [piqueserver/piqueserver#527]
Thank you for doing the hard work on this server to get it working on Linux! I have had no luck getting this off the ground until now! 

Here's a feature that I cannot find within the code and I'm sorry this is more of me asking than a feature request but it could be both...

Where can I add CFLAGS options? I only want to add -march=native

I compile things all the time but I'm sorry I don't know how to add this using python code.

**Comment by roadapathy** [comment]
I found this in code but... I really can't tell how to add my optimization

class Optimization(object):
    def __init__(self):
        self.flags = (
            'OPT',
            'CFLAGS',
            'CPPFLAGS',
            'EXTRA_CFLAGS',
            'BASECFLAGS',
            'PY_CFLAGS',
        )
        self.state = sysconfig.get_config_vars(*self.flags)
        self.config_vars = sysconfig.get_config_vars()

**Comment by NotAFile** [comment]
I assume you've tried setting those things as env vars?

**Comment by roadapathy** [comment]
No, but that's because I don't fully understand how Python works and so that's my own fault  I did, however, compile Python 3.7.x using those flags. If that's the best I can do then that's fine. If anybody else has more suggestions then please let me know.

**Comment by roadapathy** [comment]
I learned that by compiling Python 3 with the GCC flags to optimize the code that it in turn passes those flags over to the binaries produced during setup of the server. The problem was that 3.7.x Python may not have worked. Not because the code is incompatible with 3.7.x but probably because I compiled it with some of the wrong options needed. Thank you though.
