### ISSUE TITLE
Error with pkgver() during installation from AUR 

### ISSUE THREAD

**Issue by yachmenka** [piqueserver/piqueserver#529]
**Describe the bug**
AUR version of piqueserver doesn't install correctly.

**To Reproduce**
1. Download AUR snapshot.
2. Run command  'makepkg -sri' 
3. See error:
==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: 0.2756.v0.1.3-440-gef7571f7

**Comment by NotAFile** [comment]
The aur package is managed externally by @swalladge, so is out of scope for this repository.

**Comment by swalladge** [comment]
@yachmenka Thanks for the report. The pkgver() function has been updated so this error won't happen any more. In future, please leave a comment on https://aur.archlinux.org/packages/piqueserver-git/ to report issues. :smile:
