### ISSUE TITLE
Asyncio Mystery Bug

### ISSUE THREAD

**Issue by Sonicscream** [piqueserver/piqueserver#551]
**Describe the bug**
I honestly don't have one other than something made all of these errors appear in console one day.

**To Reproduce**
I can't reproduce it, it happens on its own without any apparent cause or effect while people are playing.

**Expected behavior**
Not to see these seemingly random error messages.

**Stack Trace or logs**
https://pastebin.com/vHbb90Qn

**Server (please complete the following information):**
Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-957.12.2.el7.x86_64
Piqueserver: latest from master
Python: version 3.6

**Additional context**
It started happening after I updated piqueserver where the latest commit was something about asyncio. My installation before that probably was a month or two out of date.

If you need more stack trace samples, I can provide.

**Comment by NotAFile** [comment]
As this is likely caused by a script, it would be interesting if you could narrow it down to one.

**Comment by NotAFile** [comment]
Did you find the cause?

**Comment by Sonicscream** [comment]
Nope. I do not use that OS or python anymore and do not see this error anymore either.
