### ISSUE TITLE
"Module not found" when importing script

### ISSUE THREAD

**Issue by MilkyPL** [piqueserver/piqueserver#552]
**Describe the bug**
I'm trying to load this script https://pastebin.com/dLNAqdP1 but after placing it in the scripts directory and adding it to the config I get this message `(script 'blockweapon.py' not found: ModuleNotFoundError("No module named 'blockweapon'"))`

**To Reproduce**
1. place the blockweapon.py script into the scripts directory
2. add blockweapon to scripts in the config
3. run piqueserver

**Expected behavior**
Script should work

**Stack Trace or logs**
`Warning: you are running on an unsupported Python version.
The server may not run correctly.
Please see https://github.com/piqueserver/piqueserver/wiki/Supported-Environments for more information.
Loading config from '/home/spades/.config/piqueserver/config.toml'
(script 'blockweapon.py' not found: ModuleNotFoundError("No module named 'blockweapon'"))
2019-11-25 15:21:16+0000 [-] Log opened.
2019-11-25 15:21:16+0000 [-] Generating map 'classicgen #312864299'...
2019-11-25 15:21:17+0000 [-] Map loaded successfully.
2019-11-25 15:21:17+0000 [-] Retrieving external IP from 'https://services.buildandshoot.com/getip' to generate server identifier.
2019-11-25 15:21:18+0000 [-] Started server...`

**Server:**
 - OS/Version: Fedora 30 (Python 3.7.5)
 - Piqueserver Version: 0.1.3

**Comment by MilkyPL** [comment]
Turns out I had to put it in both (.json and .toml) config files, but that deserves a separate issue.

**Comment by NotAFile** [comment]
Only one of .json and .toml is read. If one is found, it ingores the other. So that makes little sense.
