### ISSUE TITLE
Incomplete doc generation

### ISSUE THREAD

**Issue by 1AmYF** [piqueserver/piqueserver#561]
Looking at https://docs.piqueserver.org/en/latest/piqueserver.game_modes.html, it seems that some parts were omitted. Like the doc from the [infiltration script](https://github.com/piqueserver/piqueserver/blob/db54d1bf4af8b4adf61e1fb8a6945331a68fdfe8/piqueserver/game_modes/infiltration.py), the push mode options also don't show up. Couldn't see anything unusual in the underlying [rst file](https://github.com/piqueserver/piqueserver/blob/f9468d4a402f60a41b4672ad456a33dc23b1f946/doc/piqueserver.game_modes.rst) so far.

**Comment by NotAFile** [comment]
It's probably a good idea to change this to be on a separate page that just shows the docstrings anyway

**Comment by NotAFile** [comment]
This is now fixed
