### ISSUE TITLE
Bans broken

### ISSUE THREAD

**Issue by Jipok** [piqueserver/piqueserver#579]
**To Reproduce**
1. Join Self Hosted Game
2. Run command  '/ban #0'
3. Try reconnect
```
File "piqueserver/player.py", line 55, in on_connect
  name, reason, timestamp = self.protocol.bans[client_ip]
ValueError: too many values to unpack (expected 3)
```
5. Restart server
6. Banlist will be cleared. Although time has not come yet

 - OS/Version: Void Linux
 - Piqueserver Version: from master branch
 - Installation Method: git

**Comment by NotAFile** [comment]
fixed in 0b95c7f
