### ISSUE TITLE
Flag gets stuck

### ISSUE THREAD

**Issue by Jipok** [piqueserver/piqueserver#586]
1. `advance_on_win = false` and `game_mode = "ctf"`
2. player1 captures `max_score-1` flags.
3. player1 take flag
4. player2 take flag
5. player1 capture flag
6. on_game_end. but the score is not reset. bug???
7. **Bug**: For all connected players, player2 will walk with a flag that cannot be captured. Neither killing, nor changing the team will help. Only newly connected players will see the correct flag position.

**Comment by NotAFile** [comment]
This is interesting because multiple games on one map definitely used to work. But I don't know how it is supposed to be signaled at a protocol level. I can't find any code in `BetterSpades` or `OpenSpades` that would allow this to happen.

Paging @yvt @rcnly @xtreme8000 for help.

**Comment by yvt** [comment]
From what I see, `reset_game`, before sending `IntelCapture` out with `winning = True`, resets both flags' positions:
https://github.com/piqueserver/piqueserver/blob/cf895aa4df8285f30343973610494dd072b44f36/pyspades/server.py#L277-L284
https://github.com/piqueserver/piqueserver/blob/cf895aa4df8285f30343973610494dd072b44f36/pyspades/team.py#L40-L46
But neither of [OpenSpades](https://github.com/yvt/openspades/blob/e1756fe892c60692a93da1132d7747a145e4aad4/Sources/Client/NetClient.cpp#L1385) nor [BetterSpades](https://github.com/xtreme8000/BetterSpades/blob/f970167018fb4ca14911208eaf1d29ac916a69e5/src/network.c#L733) do that, hence the desynchronization between the server and the client. I don't know how the vanilla client handles this situation.

I suggest calling `drop_flag` for the other team's intel-holder in `reset_game` before calling `self.team_N.initialize()`. This should work for all clients.

**Comment by NotAFile** [comment]
@yvt `drop_flag` will prevent the intel from getting stuck, but the scores will unfortunately still be incorrect. I suppose that does mitigate the worst of the issue though.

I'd really like to know what voxlap does, but I can't get it running on my system.

**Comment by yvt** [comment]
I'm checking the voxlap client's code now ... (since I'm too lazy to perform the reproduction steps) It seems that the voxlap client resets both team scores and intels, meaning it folllows the server's behavior and thus doesn't have this problem.

**Comment by NotAFile** [comment]
I think f existing clients don't implement this anyway and need special handling, we might better fix this using a "reset score" protocol extension.

**Comment by xtreme8000** [comment]
Team score on win is now reset as of https://github.com/xtreme8000/BetterSpades/commit/a996f93c587591367b8b2896f2ecd1f39f7f776a
