### ISSUE TITLE
Can't join local server

### ISSUE THREAD

**Issue by LEFTazs** [piqueserver/piqueserver#597]
**Describe the bug**
I've set up piqueserver using Docker, as described in the documentation. Unfortunately, when I try to connect to it, with any client, it fails with an "Unknown Error".
The logs also didn't contain anything that might relate to errors.

**To Reproduce**
1. Set up piqeserver using Docker, as described in the docs
2. Try to join from the same PC to the server

**Server (please complete the following information):**
 - OS/Version: Windows 10
 - Piqueserver Version: latest Docker puplished image
 - Installation Method: Docker

**Client (if relevant)**
 - Name: Build and Shoot 1.2, OpenSpades 0.1.3

**Additional context**
As I said, I want to run the server and the client on the same PC. This might be what causes the problem?

**Comment by LEFTazs** [comment]
I figured it out, I had to join to this: "aos://16777343"
The other problem was with my configuration, the config used the 8001 port, I changed it to 32887, to accommodate to the docker setup.

**Comment by feikname** [comment]
By the way you can convert any IP address to the AoS encoding and vice-versa using [this online tool](https://noway.github.io/aos-to-address/).
