### ISSUE TITLE
Linux packages

### ISSUE THREAD

**Issue by feikname** [piqueserver/piqueserver#6]
Linux packages for the most popular distros should be provided in future versions

 * .deb and ppa for Debian-based distros
 * AUR package for Arch Linux

**Comment by swalladge** [comment]
This will probably depend on #1 (possibility to install as a pip module) - once that is done it will be simple to create package build scripts.

**Comment by swalladge** [comment]
I'm currently working on an AUR package - stay tuned!

**Comment by swalladge** [comment]
This probably doesn't need to be worried about from our end - distro packages can always be created by maintainers who are interested. However, perhaps we could consider creating a flatpak, appimage, and/or snap for it.

**Comment by NotAFile** [comment]
I think pip package is fine, really. We should make a *proper* installation guide though, with service user and systemd config and stuff.

**Comment by swalladge** [comment]
Closing because this is installable via pip now and it can be the job of package maintainers to create/maintain packages for linux distros.
