### ISSUE TITLE
Fix usages of `ServerProtocol.send_contained` to use broadcast_contained

### ISSUE THREAD

**Issue by Conticop** [piqueserver/piqueserver#602]
**Describe the bug**
A quick look at [`rollback.py`](https://github.com/piqueserver/piqueserver/blob/master/piqueserver/scripts/rollback.py) revealed that its protocol is still using a deprecated function [`ServerProtocol.send_contained`](https://github.com/piqueserver/piqueserver/blob/master/pyspades/server.py#L181). (4 usages in total.)
There may be other scripts which still use this deprecated function.

**Stack Trace or logs**
> use of deprecated send_contained, use broadcast_contained instead

**Server:**
- Latest master.

**Additional context**
There is also [`BaseConnection.send_contained`](https://github.com/piqueserver/piqueserver/blob/master/pyspades/protocol.py#L47) which is a separate function (and it is not deprecated).
So this is only relevant to usages on the *protocol* class.

**Comment by NotAFile** [comment]
Yeah, that's why we changed the name of the function. It was confusing that both were called `send_contained`.
