### ISSUE TITLE
analyse.py doesn't work

### ISSUE THREAD

**Issue by EvgenZhaba** [piqueserver/piqueserver#605]
** Describe the bug **
analyse.py doesn't work

** To Reproduce **
1. Add to config analyze.py
2. Try /an #0

https://github.com/piqueserver/piqueserver/commit/7f9967577fddb97fbe70956b2c46e051fa0fd721#diff-097aab312da95e481791cc3b44035e91fde68aee3e184bb430f6f60b96afdf70
this commit fixed "protocol.players" to "protocol.players.values()"

but in the file https://github.com/piqueserver/piqueserver/blob/master/piqueserver/scripts/analyze.py line 35 "if player not in protocol.players:" has not been fixed.
Because of this, the command "/an# 0" (to player #0 for example) does not work! Writes that "Target player is required"

**Comment by swalladge** [comment]
@EvgenZhaba a fix for this issue was merged in https://github.com/piqueserver/piqueserver/pull/606 ; can you confirm if this fixes the issue for you? :)

**Comment by EvgenZhaba** [comment]
@swalladge Yes, this is a good solution. Thanks!
