### ISSUE TITLE
bug with disabling web server logging

### ISSUE THREAD

**Issue by EvgenZhaba** [piqueserver/piqueserver#607]
**Describe the bug**
I tried to disable logging in the [status_server] block in config, but piqueserver was unable to start the web server . Everything else is in the default config. The error appears only when I stop piqueserver.
https://github.com/piqueserver/piqueserver/blob/1.0.x/piqueserver/config/config.toml#L269 "logging = false"

**To Reproduce**
1. install piqueserver (pip3 version)
2. copy default config
3. in config: replace line "logging = true" to "logging = false"
4. run piqueserver
5. stop piqueserver (i use ctrl-c)

**Stack Trace or logs**
https://gist.github.com/EvgenZhaba/64e1dc63ef4c6b74b30df2fd031d6179

maybe a bug somewhere here: https://github.com/piqueserver/piqueserver/blob/1.0.x/piqueserver/statusserver.py#L154

**Comment by NotAFile** [comment]
Does it work when you change the log level? Really, this option should not exist anymore...

**Comment by EvgenZhaba** [comment]
@NotAFile Messages from the web server are displayed at the "info" level, so if I use the "warn, error, critical" logging level, then everything seems to be fine, as if the web server does not log.
