### ISSUE TITLE
Bans seem to be disappearing

### ISSUE THREAD

**Issue by Rakete175** [piqueserver/piqueserver#619]
**Describe the bug**
A description of what the bug is.
Bans are disappearing and already banned people can sometimes join again.

**To Reproduce**
1. Create a server
2. Ban people for permanent duration
3. (Maybe restart the server)
4. Wait until they rejoin

**Expected behavior**
A description of what you expected to happen.
Bans should persist

**Stack Trace or logs**

https://gist.github.com/Rakete175/4c7b9e3ca30413ba53422facdd04dfbb

**Server (please complete the following information):**
 - OS/Version: CentOS7
 - Piqueserver Version: 1.0.0
 - Installation Method: pip3

**Client (if relevant)**
 - Name: [e.g. OpenSpades, BetterSpades]
 - Version: [e.g. 1.3.0]

**Additional context**
The gist shows a problem which might be related to that (32780 -> 32771 bans within 18 hours)

**Comment by lokka30** [comment]
We _appear_ to be having this issue as well on The Hallway, although I am uncertain. Lots of bans go in and out, so it's difficult to keep track.

**Comment by NotAFile** [comment]
Interesting. I presume this is some kind of mistake in the ban vacuum code? Or perhaps a mistake in serialization.

WIth debug log level, it would be possible to see if any bans were removed by the ban vacuum.

**Comment by Rakete175** [comment]
Thanks for your answer! 
Now I used the  "debug" loglevel for a few hours and when I search for the word "ban*" I get the following results:

22149:2021-04-14T05:27:43+0200 [piqueserver.server#info] starting ban vacuum with 32486 bans
22150:2021-04-14T05:27:43+0200 [piqueserver.server#debug] ban vacuum took 0.35 seconds, removed 3 bans
22151:2021-04-14T05:27:44+0200 [piqueserver.server#debug] saving 32483 bans took 0.47 seconds
32268:2021-04-14T11:27:43+0200 [piqueserver.server#info] starting ban vacuum with 32483 bans
32269:2021-04-14T11:27:43+0200 [piqueserver.server#debug] ban vacuum took 0.23 seconds, removed 3 bans
32270:2021-04-14T11:27:44+0200 [piqueserver.server#debug] saving 32480 bans took 0.43 seconds

**Comment by NotAFile** [comment]
Interesting that it's removing exactly three every time

**Comment by Rakete175** [comment]
Update:
I got the idea that I could log, who these bans are.
And interestingly it were always the same entries which were removed 🤔

The ban entries were the following:
['Spark', ': norecoil hack', 792681.270316433]
['Jeeves', ': norecoil hack', 793213.437570014]
['Lemon', ': norecoil hack', 793303.73371844]

I got the idea to just delete them manually and now it does not show the ban vacuum bug anymore.The only difference  I noticed between these three entries and the others were that their reason started with a ": ".
However, I can't say yet to what extent new permabans of players are lasting. I will give an update about that.

**Comment by NotAFile** [comment]
Are those `: norecoil hack` bans caused by a script? The numbers are very suspiciously in the range of monotonic timestamps. However all of our code appears to correctly use absolute timestamps. The only way that could happen is something external modifying the `self.bans` variable instead of using the correct `add_ban` api.

**Comment by DryByte** [comment]
@Rakete175 can you confirm if this still happens?

**Comment by Rakete175** [comment]
From my experience this seems to be fixed since https://github.com/piqueserver/piqueserver/commit/e004b50e2896a8b263e901fd3a9052555b1529a4. 
Have you encountered any disappearing bans after that? If not I will close this issue

**Comment by DryByte** [comment]
No, just making sure this can be closed... Your results seems to be different from the common disappearing issue, so i though it was good to ask if that commit actually fixed this.

Thank you.
