### ISSUE TITLE
Add .gitattributes file for consistency

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#62]
Currently some files have dos line endings, while others have unix. We need to add a `.gitattributes` file to the repo with rules for which line endings for the files. This will allow git to automatically manage the line endings for files and avoid problems when developers are working on piqueserver from different editors or operating systems.

https://help.github.com/articles/dealing-with-line-endings/ could be a helpful article for going about it.

**Comment by feikname** [comment]
I wrote about that some time ago [here](https://github.com/piqueserver/piqueserver/wiki/Contributing-%28developer%29). Specifically:
 * The [EOL](https://en.wikipedia.org/wiki/Newline) (End-of-line) character for the file types below must be LF (\n)
   * Python and Cython scripts (`.py` and `.pyx`)
   * C and C++ scripts (`.c`, `.cpp`, `.h`)
   * Shell scrips (`.sh`, `.bash`)
 * The [EOL](https://en.wikipedia.org/wiki/Newline) (End-of-line) character for the file types below must be CRLF (\r\n)
   * Windows scripts (`.bat`, `.ps1`)

Does everyone agree with those?

**Comment by swalladge** [comment]
We should also add a `.editorconfig` file with the conventions specified. http://editorconfig.org/

**Comment by swalladge** [comment]
Fixed in #70
