### ISSUE TITLE
Should we block no-name players in nosharp.py?

### ISSUE THREAD

**Issue by kmsiapps** [piqueserver/piqueserver#63]
It seems that aloha.pk applied script similar to nosharp.py, which blocks no-name players.
But some people are claiming that it isn't necessary, and the same problem could occur to piqueserver.
(http://aloha.pk/index.php?topic=9206.0)

What do you think about this?

**Comment by swalladge** [comment]
I agree - blocking players with illegal names is important. Who wants to play on a server where everyone has empty string names or stupidly long names, or names designed to mess up the chat interface? I could even argue that this should be core server functionality, not just optional in a script...

Also - it seems that the `nosharp.py` script already blocks no-name players. Are you then suggesting the nosharp script remove this functionality? (or refactor into a new script?) Side note - is it possible to send a message with disconnect to say the reason why the kick happened?

**Comment by feikname** [comment]
Maybe we should move `nosharp.py` implementation to `bugfix.py`?

Also, since the name itself is bugfix, I think it should be embedded in piqueserver and not optional.

**Comment by swalladge** [comment]
whoa there's a bugfix script?!?! Definitely sounds like a good idea to implement those in the core server.

**Comment by kmsiapps** [comment]
@swalladge It already blocks no-name player, but I wanted to hear the opinions of others ;)

BTW, Providing reason for kicking seems impossible. self.disconnect() only works with pre-defined messages, such as ERROR_BANNED and ERROR_KICKED etc. It doesn't work when I tried custom strings.

**Comment by noway** [comment]
Kicking with no reason is acceptable practice. Yes, should be implemented in the core.

So is that correct that we should block user names with `#` and empty user names?

What about emoticons though? They seem to be alright. Always can be referenced with user id unless there is a `#` in them.

**Comment by kmsiapps** [comment]
So, the reason why we prevent # and empty names is to allow votekick them with their name, right? 
If other participants agree, we should continue to block them, then.

**Comment by NotAFile** [comment]
If I understood it correctly, the reason we want block empty or too long names is "it's annoying", the reason we block # is that it makes it impossible to ban them.

**Comment by feikname** [comment]
I think I've seen somewhere that the reason long names should be blocked is because of a bug in the original client that made impossible to see their IDs, making them also impossible to ban.

**Comment by noway** [comment]
yes that's sounds like truth

**Comment by swalladge** [comment]
Perhaps there's another alternative. I don't know if it would be possible, but if an invalid username was detected, the server could put the player is some 'lock' state, and send a chat message to say 'please change your username'. That way players don't get kicked for no apparent reason.

**Comment by kmsiapps** [comment]
@swalladge We would put them on spectator team. I'll try..

**Comment by kmsiapps** [comment]
@feikname It seems long-name issue is fixed on pyspades. I tested with "abcdefghijklmnopqrstuv" but pyspades recognizes it as "abcdefghijklmno"

**Comment by swalladge** [comment]
Fixed in #67
