### ISSUE TITLE
Map name doesn't change when in arena game mode and doesn't automatically connect to master

### ISSUE THREAD

**Issue by 100best** [piqueserver/piqueserver#630]
**Describe the bug**
The map name doesn't change when in arena game mode and doesn't automatically connect to master

**Stack Trace or logs**
https://pastebin.com/4UsE55ad

**Server (please complete the following information):**
 - OS/Version: FreeBSD 13.0-RELEASE-p1
 - Piqueserver Version: v1.0.0-82-gc357d04
 - Installation Method: git

**Comment by NotAFile** [comment]
It's hard to say exactly what's going on here since arena modifies so much stuff and you seem to be running a version with your own patches on top

**Comment by 100best** [comment]
**Stack Trace or logs**
[arena.py change map error](https://pastebin.com/tj91nirp)

I tried commenting this line out and it appears to have fixed it.

Line 484: `return protocol.on_map_change(self, map)` in `arena.py`

**Comment by DryByte** [comment]
This can be closed, i guess.
