### ISSUE TITLE
Implement bugfix.py script fixes in core server

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#64]
As brought up in issue #63 - the server shouldn't rely on plugins or optional scripts to prevent crashes or fix bugs. I propose we investigate the reasons behind the fixes in `bugfix.py`, and any other 'bugfix' scripts and attempt to fix them in piqueserver itself.

**Comment by kmsiapps** [comment]
I found this script, which piqueserver doesn't have :
[nospadingwalls.zip](https://github.com/piqueserver/piqueserver/files/752774/nospadingwalls.zip)

This script would help bug fixes, too.

**Comment by swalladge** [comment]
@kmsiapps that's neat - I can integrate that in the core server pretty easily, but I'm wondering if that's still a bug - need to play test to see if it's still possible to hit a player behind/through a wall.

**Comment by NotAFile** [comment]
@swalladge I think it is possible, it's just that most servers have this script installed.

**Comment by swalladge** [comment]
Ideally the core server should run fine without any scripts at all (ie. vanilla), so imho if the server has the potential to crash without the script, then it should be implemented in the core.

**Comment by swalladge** [comment]
Fixed in #69. Integration of other bugfixes and discussion can happen in new issues or pull requests.
