### ISSUE TITLE
Implement OpenSpades new packet types

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#66]
OpenSpades has added a number of new packet types, they should be implemented in piqueserver.

https://github.com/yvt/openspades/wiki/Network-Protocols

**Comment by noway** [comment]
Definitely very important one, big adoption driver. Can be put off to the release after the next though, because OS hasn't had a release with new packets yet.

**Comment by feikname** [comment]
We can change the milestone if it isn't possible to ship 0.1.0 with them, but I'd certainly prefer to have the new packets implemented in 0.1.0.

**Comment by kmsiapps** [comment]
It would be nice if we have **Message Type** attribute on send_chat like this : `self.send_chat('This is server alert', notice)`

**Comment by NotAFile** [comment]
That would be good because it would be backwards compatible, but something like python `logging` module would be good too. (`logging.info()`, `logging.error`). This could then integrate with the version detection code to send different chat messages depending on if the client supports notices or not.
