### ISSUE TITLE
Replace banlist in default config with something that has actually been updated in the last 5 years

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#71]
The title pretty much. The spadille banlist does not show any dates or times, but it is very short and shows many players like "GreaseMonkey" (@iamgreaser) who I know have not been playing for years, so I presume this list is neither active nor useful.

**Comment by 1AmYF** [comment]
Yes, that blacklist service is not in use since 2012 or 2013. As there is no equivalent available, i would suggest to set the default for "ban_subscribe" to false.

**Comment by NotAFile** [comment]
Alternatively, we can host our own. It's not hard, it's basically just a webserver, right? Does Aloha have banpublish on? If so we can probably take theirs.

**Comment by izzy808** [comment]
feel free to use aloha's. my only concern is server owners not having the ability to remove any subscribed IPs from their servers. a feature to whitelist specific IPs would be a lot better than disabling the entire list.

**Comment by swalladge** [comment]
Can this be closed since we ship piqueserver with bansubscribe disabled by default? Perhaps we could add a list of any public ban subscribe servers to the docs/wiki in future.
