### ISSUE TITLE
No message size limit

### ISSUE THREAD

**Issue by utf-4096** [piqueserver/piqueserver#731]
**Describe the bug**
The server does not have a limit to how long a message can be. This is a big problem, for multiple reasons:
- it lets players spam chat a lot in a single message
- it lets attackers pollute logs
- it can let a player lag OpenSpades users significantly (large messages freeze it for a few seconds)
- it can lag the server and cause players to time out

**To Reproduce**
1. Join the server, any game mode works
2. Send a very long message (8,000,000+ characters) many times using a modified client or script
3. Get disconnected from the server for timing out

Server usually recovers quickly (not so much on slower CPUs) but the message can be sent over and over to freeze it entirely.

**Expected behavior**
Server truncates messages to a more reasonable size, like 1000 characters.

**Server (please complete the following information):**
 - OS/Version: Void Linux
 - Piqueserver Version: 1.0.0
 - Installation Method: git

**Client (if relevant)**
 - Name: OpenSpades
 - Version: 0.1.5

**Comment by DryByte** [comment]
This can be closed, i guess
