### ISSUE TITLE
Does Piqueserver Support Bot? (docker compose)

### ISSUE THREAD

**Issue by tydaytygx** [piqueserver/piqueserver#751]
**Describe the bug**
Import basicbots to piqueserver but failed

**To Reproduce**

1. add basicbots to config.toml
```
scripts = [
  "piqueserver.scripts.votekick",
  "piqueserver.scripts.map_extensions",
  "piqueserver.scripts.disco",
  "piqueserver.scripts.trusted",
  "piqueserver.scripts.ratio",
  "piqueserver.scripts.aimbot2",
  "piqueserver.scripts.welcome",
  "piqueserver.scripts.airstrike2",
  "piqueserver.scripts.basicbots"
]
```
3. start the server

**Expected behavior**
Bot should work.

**Stack Trace or logs**

```log
Error while loading script piqueserver.scripts.basicbots: ImportError("cannot import name 'input_data'",)
        Traceback (most recent call last):
          File "/usr/local/bin/piqueserver", line 33, in <module>
            sys.exit(load_entry_point('piqueserver==1.0.0', 'console_scripts', 'piqueserver')())
          File "/usr/local/lib/python3.6/site-packages/piqueserver-1.0.0-py3.6-linux-x86_64.egg/piqueserver/run.py", line 262, in main
            server.run()
          File "/usr/local/lib/python3.6/site-packages/piqueserver-1.0.0-py3.6-linux-x86_64.egg/piqueserver/server.py", line 961, in run
            script_names, script_dir)
          File "/usr/local/lib/python3.6/site-packages/piqueserver-1.0.0-py3.6-linux-x86_64.egg/piqueserver/extensions.py", line 105, in load_scripts_regular_extension
            return load_scripts(script_names, script_dir, 'script')
        --- <exception caught here> ---
          File "/usr/local/lib/python3.6/site-packages/piqueserver-1.0.0-py3.6-linux-x86_64.egg/piqueserver/extensions.py", line 82, in load_scripts
            spec.loader.exec_module(module)
          File "<frozen importlib._bootstrap_external>", line 678, in exec_module
            
          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
            
          File "/config/scripts/basicbots.py", line 37, in <module>
            from pyspades.server import input_data, weapon_input, set_tool, grenade_packet
        builtins.ImportError: cannot import name 'input_data'
```
**Server (please complete the following information):**
 - OS/Version: [Ubuntu 20.04]
What I have tried:
using docker-compose to bring up the server.(python 3.6-alpine in the image from piqueserver/piqueserver:master)
using docker-compose to bring up the server.(python 3.7-alpine in the image modify from piqueserver/piqueserver:master)

**Additional context**
Adding airstrike2 and something else runs well, but with bot scripts like bot.py, basicbot.py and ABBS.py I receive stack trace like the log above, and the **addbot** command is not available. Did I miss any dependencies? Thanks for your help!

**Comment by DryByte** [comment]
Hey, looks like you didn't ported the scripts for piqueserver, i think you is using the pyspades/pysnip version of that scripts... Remember, the scripting api is different: https://docs.piqueserver.org/en/latest/porting.html

In this directory you can find basicbots script ported to piqueserver, for ABBS and bot.py you need to port them yourself, or find a ported version somewhere.

**Comment by tydaytygx** [comment]
> Hey, looks like you didn't ported the scripts for piqueserver, i think you is using the pyspades/pysnip version of that scripts... Remember, the scripting api is different: https://docs.piqueserver.org/en/latest/porting.html
> 
> In this directory you can find basicbots script ported to piqueserver (https://github.com/piqueserver/piqueserver-extras), for ABBS and bot.py you need to port them yourself, or find a ported version somewhere.

Thank you!  I suddenly realized I am using the old  pyspades/pysnip version, looks like I miss the important part of the doc.
Now the scripts works well. How could I auto add bot on the map start? I see many server on

**Comment by DryByte** [comment]
Probably they are using ABBS for that, but you can also write a piece of code to do that using the on_map_start event.

**Comment by tydaytygx** [comment]
> code to do that using the on_map_sta

Thanks for your suggestion.
