### ISSUE TITLE
Re-licensing to AGPLv3?

### ISSUE THREAD

**Issue by 100best** [piqueserver/piqueserver#84]
[Why the Affero GPL](https://www.gnu.org/licenses/why-affero-gpl.html) and [GNU Affero General Public License](https://www.gnu.org/licenses/agpl.html)...  Basically sounds like the difference from the GNU GPLv3  is it requires that if a server operator makes a modified version he has to publish the modified version which the "[GNU General Public License, version 3](https://www.gnu.org/licenses/gpl.html)" doesn't require.

**Comment by NotAFile** [comment]
I don't think we can legally do that without the permission of all copyright holders. Even then, I don't think this would be a great idea.

**Comment by noway** [comment]
But we don't specifically want to force server holders to publish their changesets. If anything, that just add maintainance burden. Having it as an opt-in ("PRs are welcome" kinda thing) is more beneficial, right?

**Comment by swalladge** [comment]
@noway Agreed. Especially since many plugins require editing the source code to modify parameters and behaviour - would have the potential to scare away server admins.

**Comment by NotAFile** [comment]
Requring all server owners to publish source code would be a nightmare.

We don't have the means to enforce it anyway.

Even if we did, we can't relicense the software, since we do not have copyright on all parts.

Closing this for now.
