### ISSUE TITLE
Delete aimblock.py

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#94]
As far as I can tell, `scripts/aimblock.py` by @iamgreaser attempts to use three heuristics:

 1. "if one changes target, determine how accurate the gun is with respect to the head" – which is disabled because of too many false positives
 2. "if one gets a lot of kills quickly it will warn the admins over IRC"
 3. "kick people who jerk conviniently backwards onto their targets" – Not Implemented

So currently all this script does is warn when somebody gets kills very fast. `aimbot2` all these and more heuristics, which makes this script very much pointless IMO.

**Comment by NotAFile** [comment]
since there has been no response I've just gone ahead and deleted this

**Comment by noway** [comment]
I do agree that cleaning up those legacy scripts is a good idea. The less scripts there are and the higher quality/quantity ratio is, the better.
