### ISSUE TITLE
Scripts don't get updated after initial --copy-config

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#95]
The title pretty much. Copying over the scripts means they won't get updated in future.

**Comment by swalladge** [comment]
Something to note: we probably want to avoid the case where updated scripts overwrite any modifications users make to the script files.

**Comment by NotAFile** [comment]
Ideally we'd do that by just not copying the script file period and forcing people to use the not-yet-implemented packaging and config for plugins

**Comment by noway** [comment]
Well not really sure how it fits in rn, but for example dpkg and linux package managers suggest you to keep the config file, or overwrite it

**Comment by NotAFile** [comment]
Well, if we don't copy script files at all like we planned, this whole issue is kind of done.
