### ISSUE TITLE
piqueserver: command not found after installing from pip

### ISSUE THREAD

**Issue by Qwertie-** [piqueserver/piqueserver#96]
Every time I try to install piqueserver from pip I can never run it after because it doesn't seem to install to the right place. Where is it being placed currently?

**Comment by swalladge** [comment]
It is being installed with python's package installation system, which will install to wherever the system or you have configured it to install to. You will need to provide more information to help debug this: exact commands you have used to install and attempt to run it, your OS, python version (output of `python --version` and `pip --version` would be helpful), what your system $path is, and what else you have tried.

**Comment by Qwertie-** [comment]
My OS is ubuntu 17.04
Python is 2.7.13
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$PATH returns `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory`

I have just tried running the server from bash, I tried to find where it was installed but couldn't find anything.

**Comment by NotAFile** [comment]
I just tried it on a brand new ubuntu image and installation works fine. However, the version is very old and does not have `--copy-config` yet. That might be the issue.

    Error reading config from /home/ubuntu/.piqueserver/config.json: [Errno 2] No such file or directory: '/home/ubuntu/.piqueserver/config.json'

If this is your error, this is the issue.

**Comment by Qwertie-** [comment]
Nah thats not my issue, its not found at all
```

user@hostname~$ pip install piqueserver
Collecting piqueserver
Collecting Twisted<16.7,>=16.6.0 (from piqueserver)
Collecting Pillow<=4.0,>=3.4.2 (from piqueserver)
  Using cached Pillow-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Jinja2<2.9,>=2.8 (from piqueserver)
  Using cached Jinja2-2.8.1-py2.py3-none-any.whl
Collecting Cython<0.26,>=0.25.2 (from piqueserver)
  Using cached Cython-0.25.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting constantly>=15.1 (from Twisted<16.7,>=16.6.0->piqueserver)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted<16.7,>=16.6.0->piqueserver)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting zope.interface>=3.6.0 (from Twisted<16.7,>=16.6.0->piqueserver)
  Using cached zope.interface-4.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting olefile (from Pillow<=4.0,>=3.4.2->piqueserver)
Collecting MarkupSafe (from Jinja2<2.9,>=2.8->piqueserver)
Collecting setuptools (from zope.interface>=3.6.0->Twisted<16.7,>=16.6.0->piqueserver)
  Using cached setuptools-36.0.1-py2.py3-none-any.whl
Installing collected packages: constantly, incremental, setuptools, zope.interface, Twisted, olefile, Pillow, MarkupSafe, Jinja2, Cython, piqueserver
Successfully installed Cython-0.25.2 Jinja2-2.9.6 MarkupSafe-1.0 Pillow-4.1.1 Twisted-16.6.0 constantly-15.1.0 incremental-17.5.0 olefile-0.44 piqueserver-0.0.1 setuptools-36.0.1 zope.interface-4.4.2
user@hostname~$ piqueserver
piqueserver: command not found

```

**Comment by NotAFile** [comment]
I just accidentally found the issue by forgetting `sudo` while testing.

Pip usually installs to `/usr/local/bin`, which is in your `$PATH`. However when not run as root (without `sudo`) it (instead of failing like I'm used to) silently installs to `~/.local/bin/` instead, which is not in your `$PATH`.

Two possible solutions:
 - reinstall and add sudo this time
 - add `~/.local/bin/` to your path

**Comment by Qwertie-** [comment]
Worth mentioning in the readme as I was following that. I can't remember ever using sudo with pip before.

**Comment by NotAFile** [comment]
well, you appear to be the first and only one to have this issue. In my test runs it worked even without sudo.

**Comment by swalladge** [comment]
@Qwertie- no, when the readme says that you can install via pip, it is expected that you have previously installed python and pip, and correctly configured your system to use it. I suggest checking your specific OS's documentation for details.
